### PR TITLE
Ar hackathon repo

### PR DESCRIPTION
**Pull request by vinceliu21**
Created a folder called ARHackathons that contains all the demos from the hackathon.

### CODE REVIEW

**Comment by liaxim** [comment]
Will need to clean it up from intermediate files. Once large files get in the repo, the repo size goes up forever.

**Comment by liaxim** [comment]
@thomasflynn This PR adds 1.3+GB to the repo. Can we have a separate sxrsdk-hackathons repo or something?

**Comment by thomasflynn** [comment]
yeah, we can do that.

**Comment by thomasflynn** [comment]
https://github.com/sxrsdk/sxrsdk-hackathons

**Comment by liaxim** [comment]
https://github.com/sxrsdk/sxrsdk-hackathons/pull/1

**Pull request closed without merging**
